case class CrashInfo(
                  reportNumber: String,
                  reportSeqNo: String,
                  dotNumber: String,
                  reportDate: String,
                  reportState: String,
                  fatalities: String,
                  injuries: String,
                  towAway: String,
                  hazmatReleased: String,
                  trafficWayDesc: String,
                  accessControlDesc: String,
                  roadSurfaceConditionDesc: String,
                  weatherConditionDesc: String,
                  lightConditionDesc: String,
                  vehicleIdNumber: String,
                  vehicleLicenseNumber: String,
                  vehicleLicenseState: String,
                  severityWeight: String,
                  timeWeight: String,
                  citationIssuedDesc: String,
                  seqNum: String,
                  notPreventable: String
                )